version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/biglogger"
  schedule:
    interval: "weekly"

- package-ecosystem: "gomod"
  directory: "/constlogger"
  schedule:
    interval: "weekly"

- package-ecosystem: "gomod"
  directory: "/counter"
  schedule:
    interval: "weekly"

- package-ecosystem: "gomod"
  directory: "/emitter"
  schedule:
    interval: "weekly"
