name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - biglogger
          - constlogger
          - counter
          - dopplerclient
          - dummymetron
          - echo
          - emitter
          - envelopeemitter
          - https_drain
          - jsonspinner
          - latency
          - latency-log-cache
          - logemitter
          - lograter
          - logspinner
          - metric-server
          - postcounter
          - postprinter
          - reliability
          - rlpreader
          - rlptypereader
          - slow_consumer
          - syslog-forwarder
          - syslog_drain
          - syslog_to_datadog
          - syslogspinner
          - tcpprinter
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: ${{ matrix.dir }}/go.mod
      - run: go test -v -race ./...
        working-directory: ${{ matrix.dir }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - biglogger
          - constlogger
          - counter
          - dopplerclient
          - dummymetron
          - echo
          - emitter
          - envelopeemitter
          - https_drain
          - jsonspinner
          - latency
          - latency-log-cache
          - logemitter
          - lograter
          - logspinner
          - metric-server
          - postcounter
          - postprinter
          - reliability
          - rlpreader
          - rlptypereader
          - slow_consumer
          - syslog-forwarder
          - syslog_drain
          - syslog_to_datadog
          - syslogspinner
          - tcpprinter
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: ${{ matrix.dir }}/go.mod
      - uses: golangci/golangci-lint-action@v9.0.0
        with:
          working-directory: ${{ matrix.dir }}

  auto-merge:
    name: Auto‑Merge Dependabot PRs
    runs-on: ubuntu-latest
    # Only proceed if other jobs have succeeded
    needs:
      - unit-test
      - lint
    # Only proceed if this is a Dependabot‐created PR
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      github.repository == 'cloudfoundry/loggregator-tools'
    # Allow the job to approve and merge the PR
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Approve PR
        uses: actions/github-script@v8.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            });
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
