name: Go

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: '00 16 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
        - biglogger
        - constlogger
        - counter
        - dopplerclient
        - dummymetron
        - echo
        - emitter
        - envelopeemitter
        - https_drain
        - jsonspinner
        - latency
        - latency-log-cache
        - logemitter
        - lograter
        - logspinner
        - metric-server
        - postcounter
        - postprinter
        - reliability
        - rlpreader
        - rlptypereader
        - slow_consumer
        - syslog-forwarder
        - syslog_drain
        - syslog_to_datadog
        - syslogspinner
        - tcpprinter
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: ${{ matrix.dir }}/go.mod
    - run: go test -v -race ./...
      working-directory: ${{ matrix.dir }}

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
        - biglogger
        - constlogger
        - counter
        - dopplerclient
        - dummymetron
        - echo
        - emitter
        - envelopeemitter
        - https_drain
        - jsonspinner
        - latency
        - latency-log-cache
        - logemitter
        - lograter
        - logspinner
        - metric-server
        - postcounter
        - postprinter
        - reliability
        - rlpreader
        - rlptypereader
        - slow_consumer
        - syslog-forwarder
        - syslog_drain
        - syslog_to_datadog
        - syslogspinner
        - tcpprinter
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: ${{ matrix.dir }}/go.mod
    - uses: golangci/golangci-lint-action@v3.3.0
      with:
        working-directory: ${{ matrix.dir }}
